- hosts: all
  tasks:
     - name: stop container
       shell:  docker container stop webcon                    #name of container 
     - name: remove container
       shell: docker container rm webcont
     - name: remove docker image
       shell: docker image rm akhilesh48455/webprojectnew                       #name of images (docker images)
     - name: create new container
       shell: docker container run -itd --name webcon -p 9000:80 akhilesh48455/webprojectnew   #(docker-job>> name of jenkins job)
